[project]
name = "acp-mcpdoc-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "acp-sdk>=0.8.1",
    "beeai-framework[duckduckgo,wikipedia]>=0.1.19",
    "mcpdoc>=0.0.8",
    "pydantic-settings>=2.9.1",
]
